// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package PharmaGest;
import java.util.*;
/************************************************************/
/**
 * 
 */
public class Fournisseurs {
	/**
	 * 
	 */
	int num;
	/**
	 * 
	 */
	String nom;
	/**
	 * 
	 */
	String prenom;
	/**
	 * 
	 */
	String adresse;
	/**
	 * 
	 */
	int tel;
	/**
	 * 
	 */
	public String email;
	/**
	 * 
	 */
	public Facture facture;
	/**
	 * 
	 */
	public Stock stock;
	/**
	 * 
	 */
	
}
