// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package PharmaGest;
import java.util.*;
/************************************************************/
/**
 * 
 */
public class Médicaments {
	/**
	 * 
	 */
	public String DCI;
	/**
	 * 
	 */
	String nom;
	/**
	 * 
	 */
	public String dosage;
	/**
	 * 
	 */
	public Stock stock;
}
